Border radius and new shades
appsmithorg/design-system pull request #254
Opened 2022-11-17 03:42 UTC by albinAppsmith

## Description

> Please include a summary of the changes and which issue has been fixed. Please also include relevant motivation
> and context. List any dependencies that are required for this change.

Fixes # (issue)

> if no issue exists, please create an issue and ask the maintainers about this first

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How Has This Been Tested?

> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.

- Test A
- Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-30 01:49 UTC, tanvibhakta approved these changes

2022-11-30 02:58 UTC, tanvibhakta reviewed
In general, I see two issues in this PR that might not scale for us: 
1. There are a bunch of style.css files importing things that we can directly import in the file instead. Let's minimize those files as much as possible to avoid having a bloated css architecture.
2. The theme variables are directly being assigned to the css. When we were migrating these components, we decided to create component tokens so that it could be easy to update them. I see the component tokens being usedi some places and not in others, and it feel haphazard. Can we go back to using the tokens everywhere? https://www.notion.so/appsmith/Refactoring-Roadmap-359cbcf8e0384e819232813670859904#fc96d40d124e413699a097e0c7f12b79

2022-11-30 02:58 UTC, tanvibhakta commented on packages/design-system/src/Dropdown/styles.css
> +:root {
Same for this styles.css file

2022-12-16 03:53 UTC, tanvibhakta requested changes

2022-12-16 03:53 UTC, tanvibhakta commented on packages/design-system/src/themes/default/index.css
> +  --ads-color-fg-emphasis-plus: var(--ads-color-gray-800);
re: fg/bg - please let us use full forms of things as much as we can. It improves readability and in the era of modern IDEs makes no discernible difference in typing time.

2023-01-05 06:16 UTC, albinAppsmith commented
Closing this PR.

2023-01-05 06:16 UTC, closed without merging