feat: New design updates for v2 components
appsmithorg/design-system pull request #394
Opened 2023-03-02 05:06 UTC by albinAppsmith

## Description

Design updates after new token implementation.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can reproduce.
> Please also list any relevant details for your test configuration.
> Delete anything that is not important

- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-03 06:29 UTC, shadabbuchh commented
### Bugs in the Input component

**Input (textarea):**

- Functional:

1. Can the Label, Error msg & Desc when long not exceed the boundary of the input?
2. `endIcon` & `startIcon` should not be editable when `as` -> `textarea`
3. When positioning the Label on left, no max width is defined if large text is entered

- Design:

1. Wrong padding/gap for the input area/placeholder
2. Wrong background for input area in all states (expected is white)
3. No icon before error message & no red border

___________________________________________________________________________________________________________

**Input (input):**

- Functional:

1. When description/error message is long, the end icon shifts out of the input area.
2. Can the Label, Error msg & Desc when long not exceed the boundary of the input?
3. When positioning the Label on left, no max width is defined if large text is entered
4. When a long text is entered inside the text area, we neither see the complete text nor a horizontal scroll to view the complete text

- Design:

1. Wrong background for input area in all states (expected is white)
2. No icon before error message
3. Wrong gap between label, input area & desc for small variant

2023-03-03 09:33 UTC, shadabbuchh commented
### Bug in Button component:

1. Gap between Icon & the text in Medium Button is 4px. Expected is 8px

2023-03-03 10:21 UTC, shadabbuchh commented
### Bug in Modal component:

1. Icon button is of 34*34 size.
<img width="350" alt="Screenshot 2023-03-03 at 3 49 25 PM" src="https://user-images.githubusercontent.com/39921438/222695575-bf450253-552b-4708-a29d-ad2aa3b9d4aa.png">

2023-03-05 20:35 UTC, albinAppsmith commented
@shadabbuchh Fixed the issue you have raised... Please reverify.

2023-03-06 07:39 UTC, tanvibhakta requested changes

2023-03-07 06:33 UTC, albinAppsmith commented on packages/design-system/src/Button/Button.styles.tsx
> +    // lg: css`
Done

2023-03-07 06:35 UTC, albinAppsmith commented on packages/design-system/src/Button/Button.styles.tsx
> +  border-radius: var(--ads-v2-border-radius) !important;
Radix was overriding this. They have a flag called asChild, when we use that flag this all get neglected. So till they fix that isse we need to make it important.

2023-03-07 06:39 UTC, albinAppsmith commented on packages/design-system/src/Button/Button.styles.tsx
> +  min-width: ${({ isIconButton }) => (isIconButton ? "unset" : "isIconButton")};
This was a typo. Fixed...

2023-03-07 06:41 UTC, albinAppsmith commented on packages/design-system/src/Button/Button.tsx
>              typeof startIcon === "string" ? (
No we decided to not do that in icon... You only suggested not to do that

2023-03-07 06:42 UTC, albinAppsmith commented on packages/design-system/src/Button/Button.types.ts
> +  /** Whether the button is a icon button. */
Fixed.

2023-03-07 06:45 UTC, albinAppsmith commented on packages/design-system/src/Icon/Icon.tsx
> +export const iconSizes: Record<IconSizes, string> = {
This is not a type, this is a value mapping. And this needs to be passed to icon container and provider.

2023-03-07 06:47 UTC, albinAppsmith commented on packages/design-system/src/Input/Input.styles.tsx
> +  --input-font-size: 12px;
Fixed

2023-03-07 06:48 UTC, albinAppsmith commented on packages/design-system/src/Input/Input.styles.tsx
> +  disabled?: boolean;
Done

2023-03-07 06:49 UTC, albinAppsmith commented on packages/design-system/src/Toast/Toast.styles.tsx
> +  min-width: fit-content;
Done

2023-03-07 07:41 UTC, tanvibhakta requested changes
Everything else looks good, but since we've migrated all icons to our current assets folder and updated the names, let's not worry about passing in a custom icon in places that are using an icon.

2023-03-07 08:12 UTC, tanvibhakta approved these changes

2023-03-07 12:54 UTC, shadabbuchh commented
### Issues noticed in this PR after the latest commits:

**Input:**
1. The height of the Input -> small variant is incorrect (expected is 22px).
___________________________________________________________________________________________________________

**Callout:**
Functional:

1. How do I add new links using the default input method?
2. When the text is quite long the x icon is not completely visible
<img width="475" alt="Screenshot 2023-03-07 at 6 19 37 PM" src="https://user-images.githubusercontent.com/39921438/223426862-53ea16a0-9865-46a5-a2e1-bbd666f0e66f.png">

Design:

1. When there is a single line, the icon does not seem to be aligned with the text
<img width="145" alt="Screenshot 2023-03-07 at 6 20 13 PM" src="https://user-images.githubusercontent.com/39921438/223426968-a4b091e5-00e4-4fdf-87c9-091a68799863.png">

___________________________________________________________________________________________________________

**Tabs:**
Functional:

1. We are able to enter negative values in the notificationCount control.

Design:

1. Wrong colour for text as well as the bottom line that appears in hover state.
2. Wrong height of the notificationCount.
3. Wrong colour of the horizontal line.

2023-03-07 20:11 UTC, albinAppsmith commented
@shadabbuchh Fixed all the issue you mentioned.

- Wrong height of the notificationCount => We are using tag component here so it will follow tag component height
- Can we add an ellipsis when the tab's name is very long along with a tolltip? => We need a clarity from design team. Can do this in next phase. Please add this comment in zeplin.
- When notificationCount is set to 0 should the notif icon be seen? => made it hidden

2023-03-08 06:03 UTC, shadabbuchh commented
All identified issues have been fixed and retested.

2023-03-08 06:08 UTC, merged