chore: fix issues with dependencies, toast
appsmithorg/design-system pull request #395
Opened 2023-03-02 05:44 UTC by tanvibhakta

## Description

This PR is making small changes to the dependency tree, toast api, etc to support findings from the deduplication of toast in appsmith. 
https://github.com/appsmithorg/appsmith/pull/21087

## Type of change

- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Chore (housekeeping or task changes that don't impact user perception)

## How Has This Been Tested?

- Manual on storybook 
- Manual on main repo
- Jest
- Cypress

### Test Plan
> Add Testsmith test cases links that relate to this PR

### Issues raised during DP testing
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this PR)

## Checklist:
### Dev activity
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### QA activity:
- [ ] Test plan has been approved by relevant developers
- [ ] Test plan has been peer reviewed by QA
- [ ] Cypress test cases have been added and approved by either SDET or manual QA
- [ ] Organized project review call with relevant stakeholders after Round 1/2 of QA
- [ ] Added Test Plan Approved label after reveiwing all Cypress test

2023-03-02 14:06 UTC, albinAppsmith requested changes

2023-03-02 14:06 UTC, albinAppsmith commented on packages/design-system/src/Button/Button.tsx
> +        className={clsx(ButtonClassName, className, buttonProps.className)}
This needs to be removed

2023-03-02 14:07 UTC, tanvibhakta commented on packages/design-system/src/Button/Button.tsx
> +        className={clsx(ButtonClassName, className, buttonProps.className)}
It has been reverted.

2023-03-03 06:01 UTC, albinAppsmith approved these changes

2023-03-03 07:04 UTC, merged