Create Component-Migration-Checklist.md
appsmithorg/design-system pull request #52
Opened 2022-07-18 05:18 UTC by tanvibhakta

## Description

This PR will add our component migration guide and checklist to this repository 

## Type of change

- This change is a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-07-18 05:34 UTC, rohitagarwal88 requested changes

2022-07-18 05:34 UTC, rohitagarwal88 commented on packages/design-system/Component-Migration-Checklist.md
> +- [ ]  Create an issue for it on [appsmith/ce](http://github.com/appsmithorg/appsmith). Announce that you’re doing this on #design-system
add #team-tech channel

2022-07-18 05:34 UTC, rohitagarwal88 commented on packages/design-system/Component-Migration-Checklist.md
> +- [ ]  Create a branch to change the imports on appsmith/ce.
@tanvibhakta Mention checklist of EE repo.

2022-07-18 05:34 UTC, albinAppsmith approved these changes

2022-07-19 05:08 UTC, rohitagarwal88 requested changes

2022-07-19 05:08 UTC, rohitagarwal88 commented on packages/design-system/Component-Migration-Checklist.md
> +      - [ ] If you've migrated a component that is used a specific new places in the ee-repo, make updates there as well.
@tanvibhakta : Also, add a mandatory step to test locally on both ce & ee. Then, the developer will know is that breaking anything on ee. Then, he needs to create a branch on ee and do import changes.

2022-07-19 05:08 UTC, rohitagarwal88 commented on packages/design-system/Component-Migration-Checklist.md
> +- [ ]  Once your changes on the design-system repository has been approved and merged to release, take the beta version number of our package under ‘current tags’ from the published npm page, and rep
@tanvibhakta : QA has to verify on both ee & ce.

2022-07-26 11:26 UTC, albinAppsmith approved these changes

2022-07-27 14:05 UTC, rohitagarwal88 approved these changes

2022-07-27 14:05 UTC, merged